server:
  port: 8002

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-product?characterEncoding=utf-8&useSSL=false
    username: root
    password: zxy902
  rabbitmq:
    host: 192.168.153.100
    port: 5672
    username: rinneohara
    password: zxy902
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        register-enabled: true

aliyun:
  endpoint: oss-cn-shanghai.aliyuncs.com
  keyid: LTAI5tEfoVW4hgeYudXFgvg4
  keysecret: BdLaCuMqnBdzhxUHYbACv9oyBfwPlX
  bucketname: rinne-ssys
